// <auto-generated />
namespace Oclumen.Crawler.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedMoreAutoSentimentInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedMoreAutoSentimentInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201305060306492_AddedMoreAutoSentimentInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
