namespace Oclumen.Crawler.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedAutoGeneratedKeyToUseRecords : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.HashtagUseRecords", "Key", c => c.Long(nullable: false, identity: true));
            AddColumn("dbo.RetweetUseRecords", "Key", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.HashtagUseRecords", "Tag", c => c.String(maxLength: 1024));
            AlterColumn("dbo.RetweetUseRecords", "Tag", c => c.String(maxLength: 1024));
            AddPrimaryKey("dbo.HashtagUseRecords", "Key");
            AddPrimaryKey("dbo.RetweetUseRecords", "Key");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.RetweetUseRecords", new[] { "Key" });
            AddPrimaryKey("dbo.RetweetUseRecords", "Tag");
            DropPrimaryKey("dbo.HashtagUseRecords", new[] { "Key" });
            AddPrimaryKey("dbo.HashtagUseRecords", "Tag");
            AlterColumn("dbo.RetweetUseRecords", "Tag", c => c.String(nullable: false, maxLength: 1024));
            AlterColumn("dbo.HashtagUseRecords", "Tag", c => c.String(nullable: false, maxLength: 1024));
            DropColumn("dbo.RetweetUseRecords", "Key");
            DropColumn("dbo.HashtagUseRecords", "Key");
        }
    }
}
