// <auto-generated />
namespace Oclumen.Crawler.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedAutoGeneratedKeyToUseRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedAutoGeneratedKeyToUseRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201305062015114_AddedAutoGeneratedKeyToUseRecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
