// <auto-generated />
namespace Oclumen.Crawler.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedBaseUseRecordClassAndRetweetUse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedBaseUseRecordClassAndRetweetUse));
        
        string IMigrationMetadata.Id
        {
            get { return "201305061933543_AddedBaseUseRecordClassAndRetweetUse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
